// AriaVoice.js
// Human-sounding TTS for Aria
// Priority: Google Cloud TTS (via /api/speak) -> ElevenLabs (via /api/speak) -> Kokoro-82M v1.0 -> best available browser voice

let kokoroPipeline = null;
let kokoroLoading = false;
let kokoroFailed = false;

// Track monthly character usage to stay under the free tier limit
function checkElevenLabsBudget(text) {
  const thisMonth = String(new Date().getMonth());
  const lastReset = localStorage.getItem('elevenLabsReset');
  if (lastReset !== thisMonth) {
    localStorage.setItem('elevenLabsChars', '0');
    localStorage.setItem('elevenLabsReset', thisMonth);
  }

  const charCount = parseInt(localStorage.getItem('elevenLabsChars') || '0', 10);

  if (charCount + text.length > 9000) {
    throw new Error('Monthly limit approaching');
  }

  localStorage.setItem('elevenLabsChars', String(charCount + text.length));
}

async function serverTTSSpeak(text) {
  checkElevenLabsBudget(text);

  const response = await fetch('/api/speak', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ text }),
  });

  if (!response.ok) {
    if (response.status === 502) {
      const data = await response.json().catch(() => ({}));
      if (data.fallback === 'browser') {
        throw new Error('TTS failed, fallback to browser');
      }
    }
    throw new Error('Server TTS failed');
  }

  // PROOF: Log which TTS provider actually generated the audio
  const provider = response.headers.get('X-TTS-Provider') || 'unknown';
  const voice = response.headers.get('X-TTS-Voice') || 'unknown';
  console.log(`%c🔊 TTS Provider: ${provider} | Voice: ${voice}`, 'color: #00ff88; font-weight: bold; font-size: 14px;');
  console.log(`%c✅ CONFIRMED: Audio generated by Google Cloud TTS (server-side)`, 'color: #00ff88; font-weight: bold;');

  const audioBlob = await response.blob();
  const audioUrl = URL.createObjectURL(audioBlob);

  return new Promise((resolve) => {
    const audio = new Audio(audioUrl);
    audio.onended = () => {
      URL.revokeObjectURL(audioUrl);
      resolve();
    };
    audio.onerror = () => {
      URL.revokeObjectURL(audioUrl);
      resolve();
    };
    audio.play();
  });
}

async function initKokoro() {
  if (kokoroPipeline) return kokoroPipeline;
  if (kokoroLoading) return null;
  if (kokoroFailed) return null;

  try {
    kokoroLoading = true;
    console.log('Aria: Loading Kokoro voice...');

    const { pipeline } = await import('@huggingface/transformers');

    kokoroPipeline = await pipeline(
      'text-to-speech',
      'onnx-community/Kokoro-82M-v1.0',
      {
        dtype: 'fp32',
        device: 'wasm',
      },
    );

    kokoroLoading = false;
    console.log('Aria: Kokoro voice ready ✅');
    localStorage.setItem('ariaVoiceLoaded', 'true');
    return kokoroPipeline;
  } catch (err) {
    kokoroLoading = false;
    kokoroFailed = true;
    const msg = err?.message || String(err);
    if (msg.includes('401') || msg.includes('Unauthorized') || msg.includes('authentication') || msg.includes('403') || msg.includes('Forbidden') || msg.includes('gated')) {
      console.warn('Aria: Kokoro model is gated/requires auth, falling back to browser TTS');
    } else {
      console.warn('Aria: Kokoro failed:', msg);
    }
    return null;
  }
}

async function kokoroSpeak(text) {
  const tts = await initKokoro();
  if (!tts) throw new Error('Kokoro not available');

  const result = await tts(text, {
    voice: 'af_heart',
    speed: 0.92,
  });

  const audioCtx = new (window.AudioContext || window.webkitAudioContext)();

  const buffer = await audioCtx.decodeAudioData(result.audio.buffer.slice(0));

  return new Promise((resolve) => {
    const source = audioCtx.createBufferSource();
    source.buffer = buffer;
    source.connect(audioCtx.destination);
    source.onended = () => {
      audioCtx.close();
      resolve();
    };
    source.start(0);
  });
}

function getBestBrowserVoice() {
  const voices = window.speechSynthesis.getVoices();

  const priority = [
    'Google UK English Female',
    'Microsoft Sonia Online (Natural)',
    'Microsoft Libby Online (Natural)',
    'Microsoft Mia Online (Natural)',
    'Microsoft Zira Desktop',
    'Karen',
    'Samantha',
    'Veena',
    'Google US English',
  ];

  for (const name of priority) {
    const match = voices.find((v) => v.name.includes(name));
    if (match) return match;
  }

  return (
    voices.find((v) => v.name.toLowerCase().includes('female')) ||
    voices.find((v) => v.lang?.startsWith('en')) ||
    voices[0]
  );
}

function browserSpeak(text) {
  return new Promise((resolve) => {
    window.speechSynthesis.cancel();

    const utterance = new SpeechSynthesisUtterance(text);

    const setVoice = () => {
      utterance.voice = getBestBrowserVoice();
      utterance.rate = 0.88;
      utterance.pitch = 1.08;
      utterance.volume = 1.0;
    };

    if (window.speechSynthesis.getVoices().length > 0) {
      setVoice();
    } else {
      window.speechSynthesis.onvoiceschanged = setVoice;
    }

    utterance.onend = resolve;
    utterance.onerror = resolve;

    window.speechSynthesis.speak(utterance);
  });
}

function cleanForSpeech(text) {
  return (
    text
      .replace(/\[💡[^\]]*\]/g, '')
      .replace(/\[🎯[^\]]*\]/g, '')
      .replace(/\[⭐[^\]]*\]/g, '')
      .replace(/\[📊[^\]]*\]/g, '')
      .replace(/\[💬[^\]]*\]/g, '')
      .replace(/\[⏱️[^\]]*\]/g, '')
      .replace(/\*\*/g, '')
      .replace(/\*/g, '')
      .replace(/_/g, '')
      .replace(/[\u{1F300}-\u{1F9FF}]/gu, '')
      .trim()
  );
}

export async function ariaSpeak(text) {
  if (!text || text.trim() === '') return;

  const clean = cleanForSpeech(text);
  if (!clean) return;

  // 1) Try server TTS first (Google Cloud TTS -> ElevenLabs)
  try {
    await serverTTSSpeak(clean);
    return;
  } catch (err) {
    console.warn('Aria: Server TTS unavailable:', err.message);
  }

  // 2) Fall back to Kokoro (good quality, local)
  try {
    if (!kokoroFailed) {
      await kokoroSpeak(clean);
      return;
    }
  } catch {
    console.warn('Aria: Kokoro speak failed, using browser TTS');
    kokoroFailed = true;
  }

  // 3) Fall back to browser TTS (basic)
  await browserSpeak(clean);
}

export function stopAria() {
  window.speechSynthesis.cancel();
}

export function preloadAriaVoice() {
  const alreadyLoaded = localStorage.getItem('ariaVoiceLoaded');

  if (!alreadyLoaded) {
    setTimeout(() => {
      initKokoro().catch(() => {
        console.log('Aria: Will use browser voice');
      });
    }, 3000);
  } else {
    initKokoro().catch(() => {});
  }
}